let testdata = "algo";

let data = [
  {
    categoryId: "1",
    categoryName: "HTML",
    statsValue: 0,
    questions: [
      {
        Qid: 1,
        Qtype: "a",
        QQuest: "¿Pregunta html 1?",
        Qans: [
          { 1: "html true" },
          { 2: "html false 1" },
          { 3: "html false 2" },
        ],
      },
      {
        Qid: 2,
        Qtype: "a",
        QQuest: "¿Pregunta html 2?",
        Qans: [
          { 1: "html true" },
          { 2: "html false 1" },
          { 3: "html false 2" },
        ],
      },
      {
        Qid: 3,
        Qtype: "a",
        QQuest: "¿Pregunta html 3?",
        Qans: [
          { 1: "html true" },
          { 2: "html false 1" },
          { 3: "html false 2" },
        ],
      },
      {
        Qid: 4,
        Qtype: "a",
        QQuest: "¿Pregunta html 4?",
        Qans: [
          { 1: "html true" },
          { 2: "html false 1" },
          { 3: "html false 2" },
        ],
      },
      {
        Qid: 5,
        Qtype: "a",
        QQuest: "¿Pregunta html 5?",
        Qans: [{ 1: "html true", 2: "html false 1", 3: "html false 2" }],
      },
      {
        Qid: 6,
        Qtype: "b",
        QQuest: "¿Pregunta html 6?",
        Qans: [
          { 1: "html palabra 1" },
          { 2: "html palabra 2" },
          { 3: "html palabra 3" },
          { 4: "html palabra 4" },
          { 5: "html palabra 5" },
        ],
      },
      {
        Qid: 7,
        Qtype: "b",
        QQuest: "¿Pregunta html 7?",
        Qans: [
          { 1: "html palabra 1" },
          { 2: "html palabra 2" },
          { 3: "html palabra 3" },
          { 4: "html palabra 4" },
          { 5: "html palabra 5" },
        ],
      },
      {
        Qid: 8,
        Qtype: "b",
        QQuest: "¿Pregunta html 8?",
        Qans: [
          { 1: "html palabra 1" },
          { 2: "html palabra 2" },
          { 3: "html palabra 3" },
          { 4: "html palabra 4" },
          { 5: "html palabra 5" },
        ],
      },
      {
        Qid: 9,
        Qtype: "b",
        QQuest: "¿Pregunta html 9?",
        Qans: [
          { 1: "html palabra 1" },
          { 2: "html palabra 2" },
          { 3: "html palabra 3" },
          { 4: "html palabra 4" },
          { 5: "html palabra 5" },
        ],
      },
      {
        Qid: 10,
        Qtype: "c",
        QQuest: "¿Pregunta html 10?",
        Qans: [
          { 1: "html verdadero" },
          { 2: "html falso" },
          { 3: "html falso" },
          { 4: "html falso" },
        ],
      },
      {
        Qid: 11,
        Qtype: "c",
        QQuest: "¿Pregunta html 11?",
        Qans: [
          { 1: "html verdadero" },
          { 2: "html falso" },
          { 3: "html falso" },
          { 4: "html falso" },
        ],
      },
      {
        Qid: 12,
        Qtype: "c",
        QQuest: "¿Pregunta html 12?",
        Qans: [
          { 1: "html verdadero" },
          { 2: "html falso" },
          { 3: "html falso" },
          { 4: "html falso" },
        ],
      },
    ],
  },

  {
    categoryId: "2",
    categoryName: "CSS",
    statsValue: 0,
    questions: [
      {
        Qid: 1,
        Qtype: "a",
        QQuest: "¿Pregunta css 1?",
        Qans: [{ 1: "css true" }, { 2: "css false 1" }, { 3: "css false 2" }],
      },
      {
        Qid: 2,
        Qtype: "a",
        QQuest: "¿Pregunta css 2?",
        Qans: [{ 1: "css true" }, { 2: "css false 1" }, { 3: "css false 2" }],
      },
      {
        Qid: 3,
        Qtype: "a",
        QQuest: "¿Pregunta css 3?",
        Qans: [{ 1: "css true" }, { 2: "css false 1" }, { 3: "css false 2" }],
      },
      {
        Qid: 4,
        Qtype: "a",
        QQuest: "¿Pregunta css 4?",
        Qans: [{ 1: "css true" }, { 2: "css false 1" }, { 3: "css false 2" }],
      },
      {
        Qid: 5,
        Qtype: "a",
        QQuest: "¿Pregunta css 5?",
        Qans: [{ 1: "css true", 2: "css false 1", 3: "css false 2" }],
      },
      {
        Qid: 6,
        Qtype: "b",
        QQuest: "¿Pregunta css 6?",
        Qans: [
          { 1: "css palabra 1" },
          { 2: "css palabra 2" },
          { 3: "css palabra 3" },
          { 4: "css palabra 4" },
          { 5: "css palabra 5" },
        ],
      },
      {
        Qid: 7,
        Qtype: "b",
        QQuest: "¿Pregunta css 7?",
        Qans: [
          { 1: "css palabra 1" },
          { 2: "css palabra 2" },
          { 3: "css palabra 3" },
          { 4: "css palabra 4" },
          { 5: "css palabra 5" },
        ],
      },
      {
        Qid: 8,
        Qtype: "b",
        QQuest: "¿Pregunta css 8?",
        Qans: [
          { 1: "css palabra 1" },
          { 2: "css palabra 2" },
          { 3: "css palabra 3" },
          { 4: "css palabra 4" },
          { 5: "css palabra 5" },
        ],
      },
      {
        Qid: 9,
        Qtype: "b",
        QQuest: "¿Pregunta css 9?",
        Qans: [
          { 1: "css palabra 1" },
          { 2: "css palabra 2" },
          { 3: "css palabra 3" },
          { 4: "css palabra 4" },
          { 5: "css palabra 5" },
        ],
      },
      {
        Qid: 10,
        Qtype: "c",
        QQuest: "¿Pregunta css 10?",
        Qans: [
          { 1: "css verdadero" },
          { 2: "css falso" },
          { 3: "css falso" },
          { 4: "css falso" },
        ],
      },
      {
        Qid: 11,
        Qtype: "c",
        QQuest: "¿Pregunta css 11?",
        Qans: [
          { 1: "css verdadero" },
          { 2: "css falso" },
          { 3: "css falso" },
          { 4: "css falso" },
        ],
      },
      {
        Qid: 12,
        Qtype: "c",
        QQuest: "¿Pregunta css 12?",
        Qans: [
          { 1: "css verdadero" },
          { 2: "css falso" },
          { 3: "css falso" },
          { 4: "css falso" },
        ],
      },
    ],
  },
  {
    categoryId: "2",
    categoryName: "JS",
    statsValue: 0,
    questions: [
      {
        Qid: 1,
        Qtype: "a",
        QQuest: "¿Pregunta js 1?",
        Qans: [{ 1: "js true" }, { 2: "js false 1" }, { 3: "js false 2" }],
      },
      {
        Qid: 2,
        Qtype: "a",
        QQuest: "¿Pregunta js 2?",
        Qans: [{ 1: "js true" }, { 2: "js false 1" }, { 3: "js false 2" }],
      },
      {
        Qid: 3,
        Qtype: "a",
        QQuest: "¿Pregunta js 3?",
        Qans: [{ 1: "js true" }, { 2: "js false 1" }, { 3: "js false 2" }],
      },
      {
        Qid: 4,
        Qtype: "a",
        QQuest: "¿Pregunta js 4?",
        Qans: [{ 1: "js true" }, { 2: "js false 1" }, { 3: "js false 2" }],
      },
      {
        Qid: 5,
        Qtype: "a",
        QQuest: "¿Pregunta js 5?",
        Qans: [{ 1: "js true", 2: "js false 1", 3: "js false 2" }],
      },
      {
        Qid: 6,
        Qtype: "b",
        QQuest: "¿Pregunta js 6?",
        Qans: [
          { 1: "js palabra 1" },
          { 2: "js palabra 2" },
          { 3: "js palabra 3" },
          { 4: "js palabra 4" },
          { 5: "js palabra 5" },
        ],
      },
      {
        Qid: 7,
        Qtype: "b",
        QQuest: "¿Pregunta js 7?",
        Qans: [
          { 1: "js palabra 1" },
          { 2: "js palabra 2" },
          { 3: "js palabra 3" },
          { 4: "js palabra 4" },
          { 5: "js palabra 5" },
        ],
      },
      {
        Qid: 8,
        Qtype: "b",
        QQuest: "¿Pregunta js 8?",
        Qans: [
          { 1: "js palabra 1" },
          { 2: "js palabra 2" },
          { 3: "js palabra 3" },
          { 4: "js palabra 4" },
          { 5: "js palabra 5" },
        ],
      },
      {
        Qid: 9,
        Qtype: "b",
        QQuest: "¿Pregunta js 9?",
        Qans: [
          { 1: "js palabra 1" },
          { 2: "js palabra 2" },
          { 3: "js palabra 3" },
          { 4: "js palabra 4" },
          { 5: "js palabra 5" },
        ],
      },
      {
        Qid: 10,
        Qtype: "c",
        QQuest: "¿Pregunta js 10?",
        Qans: [
          { 1: "js verdadero" },
          { 2: "js falso" },
          { 3: "js falso" },
          { 4: "js falso" },
        ],
      },
      {
        Qid: 11,
        Qtype: "c",
        QQuest: "¿Pregunta js 11?",
        Qans: [
          { 1: "js verdadero" },
          { 2: "js falso" },
          { 3: "js falso" },
          { 4: "js falso" },
        ],
      },
      {
        Qid: 12,
        Qtype: "c",
        QQuest: "¿Pregunta js 12?",
        Qans: [
          { 1: "js verdadero" },
          { 2: "js falso" },
          { 3: "js falso" },
          { 4: "js falso" },
        ],
      },
    ],
  },

  {
    categoryId: "2",
    categoryName: "FIGMA",
    statsValue: 0,
    questions: [
      {
        Qid: 1,
        Qtype: "a",
        QQuest: "¿Pregunta figma 1?",
        Qans: [
          { 1: "figma true" },
          { 2: "figma false 1" },
          { 3: "figma false 2" },
        ],
      },
      {
        Qid: 2,
        Qtype: "a",
        QQuest: "¿Pregunta figma 2?",
        Qans: [
          { 1: "figma true" },
          { 2: "figma false 1" },
          { 3: "figma false 2" },
        ],
      },
      {
        Qid: 3,
        Qtype: "a",
        QQuest: "¿Pregunta figma 3?",
        Qans: [
          { 1: "figma true" },
          { 2: "figma false 1" },
          { 3: "figma false 2" },
        ],
      },
      {
        Qid: 4,
        Qtype: "a",
        QQuest: "¿Pregunta figma 4?",
        Qans: [
          { 1: "figma true" },
          { 2: "figma false 1" },
          { 3: "figma false 2" },
        ],
      },
      {
        Qid: 5,
        Qtype: "a",
        QQuest: "¿Pregunta figma 5?",
        Qans: [{ 1: "figma true", 2: "figma false 1", 3: "figma false 2" }],
      },
      {
        Qid: 6,
        Qtype: "b",
        QQuest: "¿Pregunta figma 6?",
        Qans: [
          { 1: "figma palabra 1" },
          { 2: "figma palabra 2" },
          { 3: "figma palabra 3" },
          { 4: "figma palabra 4" },
          { 5: "figma palabra 5" },
        ],
      },
      {
        Qid: 7,
        Qtype: "b",
        QQuest: "¿Pregunta figma 7?",
        Qans: [
          { 1: "figma palabra 1" },
          { 2: "figma palabra 2" },
          { 3: "figma palabra 3" },
          { 4: "figma palabra 4" },
          { 5: "figma palabra 5" },
        ],
      },
      {
        Qid: 8,
        Qtype: "b",
        QQuest: "¿Pregunta figma 8?",
        Qans: [
          { 1: "figma palabra 1" },
          { 2: "figma palabra 2" },
          { 3: "figma palabra 3" },
          { 4: "figma palabra 4" },
          { 5: "figma palabra 5" },
        ],
      },
      {
        Qid: 9,
        Qtype: "b",
        QQuest: "¿Pregunta figma 9?",
        Qans: [
          { 1: "figma palabra 1" },
          { 2: "figma palabra 2" },
          { 3: "figma palabra 3" },
          { 4: "figma palabra 4" },
          { 5: "figma palabra 5" },
        ],
      },
      {
        Qid: 10,
        Qtype: "c",
        QQuest: "¿Pregunta figma 10?",
        Qans: [
          { 1: "figma verdadero" },
          { 2: "figma falso" },
          { 3: "figma falso" },
          { 4: "figma falso" },
        ],
      },
      {
        Qid: 11,
        Qtype: "c",
        QQuest: "¿Pregunta figma 11?",
        Qans: [
          { 1: "figma verdadero" },
          { 2: "figma falso" },
          { 3: "figma falso" },
          { 4: "figma falso" },
        ],
      },
      {
        Qid: 12,
        Qtype: "c",
        QQuest: "¿Pregunta figma 12?",
        Qans: [
          { 1: "figma verdadero" },
          { 2: "figma falso" },
          { 3: "figma falso" },
          { 4: "figma falso" },
        ],
      },
    ],
  },

  {
    categoryId: "2",
    categoryName: "UX",
    statsValue: 0,
    questions: [
      {
        Qid: 1,
        Qtype: "a",
        QQuest: "¿Pregunta ux 1?",
        Qans: [{ 1: "ux true" }, { 2: "ux false 1" }, { 3: "ux false 2" }],
      },
      {
        Qid: 2,
        Qtype: "a",
        QQuest: "¿Pregunta ux 2?",
        Qans: [{ 1: "ux true" }, { 2: "ux false 1" }, { 3: "ux false 2" }],
      },
      {
        Qid: 3,
        Qtype: "a",
        QQuest: "¿Pregunta ux 3?",
        Qans: [{ 1: "ux true" }, { 2: "ux false 1" }, { 3: "ux false 2" }],
      },
      {
        Qid: 4,
        Qtype: "a",
        QQuest: "¿Pregunta ux 4?",
        Qans: [{ 1: "ux true" }, { 2: "ux false 1" }, { 3: "ux false 2" }],
      },
      {
        Qid: 5,
        Qtype: "a",
        QQuest: "¿Pregunta ux 5?",
        Qans: [{ 1: "ux true", 2: "ux false 1", 3: "ux false 2" }],
      },
      {
        Qid: 6,
        Qtype: "b",
        QQuest: "¿Pregunta ux 6?",
        Qans: [
          { 1: "ux palabra 1" },
          { 2: "ux palabra 2" },
          { 3: "ux palabra 3" },
          { 4: "ux palabra 4" },
          { 5: "ux palabra 5" },
        ],
      },
      {
        Qid: 7,
        Qtype: "b",
        QQuest: "¿Pregunta ux 7?",
        Qans: [
          { 1: "ux palabra 1" },
          { 2: "ux palabra 2" },
          { 3: "ux palabra 3" },
          { 4: "ux palabra 4" },
          { 5: "ux palabra 5" },
        ],
      },
      {
        Qid: 8,
        Qtype: "b",
        QQuest: "¿Pregunta ux 8?",
        Qans: [
          { 1: "ux palabra 1" },
          { 2: "ux palabra 2" },
          { 3: "ux palabra 3" },
          { 4: "ux palabra 4" },
          { 5: "ux palabra 5" },
        ],
      },
      {
        Qid: 9,
        Qtype: "b",
        QQuest: "¿Pregunta ux 9?",
        Qans: [
          { 1: "ux palabra 1" },
          { 2: "ux palabra 2" },
          { 3: "ux palabra 3" },
          { 4: "ux palabra 4" },
          { 5: "ux palabra 5" },
        ],
      },
      {
        Qid: 10,
        Qtype: "c",
        QQuest: "¿Pregunta ux 10?",
        Qans: [
          { 1: "ux verdadero" },
          { 2: "ux falso" },
          { 3: "ux falso" },
          { 4: "ux falso" },
        ],
      },
      {
        Qid: 11,
        Qtype: "c",
        QQuest: "¿Pregunta ux 11?",
        Qans: [
          { 1: "ux verdadero" },
          { 2: "ux falso" },
          { 3: "ux falso" },
          { 4: "ux falso" },
        ],
      },
      {
        Qid: 12,
        Qtype: "c",
        QQuest: "¿Pregunta ux 12?",
        Qans: [
          { 1: "ux verdadero" },
          { 2: "ux falso" },
          { 3: "ux falso" },
          { 4: "ux falso" },
        ],
      },
    ],
  },
];
export { data, testdata };
